module VerifyExamples.Examples.Primes.TrialDivisionWheel20 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Examples.Primes exposing (..)
import Generator as G







spec0 : Test.Test
spec0 =
    Test.test "#trialDivisionWheel2: \n\n    trialDivisionWheel2357\n    |> G.take 10\n    --> [ 2, 3, 5, 7, 11, 13, 17, 19, 23, 29 ]" <|
        \() ->
            Expect.equal
                (
                trialDivisionWheel2357
                |> G.take 10
                )
                (
                [ 2, 3, 5, 7, 11, 13, 17, 19, 23, 29 ]
                )