module VerifyExamples.Generator.Cons0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#cons: \n\n    cons \"a\" (fromList [\"b\", \"c\", \"d\"])\n    |> take 4\n    --> [\"a\", \"b\", \"c\", \"d\"]" <|
        \() ->
            Expect.equal
                (
                cons "a" (fromList ["b", "c", "d"])
                |> take 4
                )
                (
                ["a", "b", "c", "d"]
                )