module VerifyExamples.Generator.DropWhile0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#dropWhile: \n\n    iterate ((+) 1) 1\n    |> dropWhile ((>) 5)\n    |> take 5\n    --> [6, 7, 8, 9, 10]" <|
        \() ->
            Expect.equal
                (
                iterate ((+) 1) 1
                |> dropWhile ((>) 5)
                |> take 5
                )
                (
                [6, 7, 8, 9, 10]
                )