module VerifyExamples.Generator.Empty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#empty: \n\n    fromList [1, 2, 3, 4, 5]\n    |> drop 6\n    |> empty\n    --> True" <|
        \() ->
            Expect.equal
                (
                fromList [1, 2, 3, 4, 5]
                |> drop 6
                |> empty
                )
                (
                True
                )