module VerifyExamples.Generator.Filter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#filter: \n\n    iterate ((+) 1) 1\n    |> filter ((<) 3)\n    |> take 5\n    --> [4, 5, 6, 7, 8]" <|
        \() ->
            Expect.equal
                (
                iterate ((+) 1) 1
                |> filter ((<) 3)
                |> take 5
                )
                (
                [4, 5, 6, 7, 8]
                )