module VerifyExamples.Generator.Foldl1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#foldl: \n\n    fromList [ 1, 2, 3, 4, 5 ]\n    |> foldl (::) []\n    --> [ 5, 4, 3, 2, 1 ]" <|
        \() ->
            Expect.equal
                (
                fromList [ 1, 2, 3, 4, 5 ]
                |> foldl (::) []
                )
                (
                [ 5, 4, 3, 2, 1 ]
                )