module VerifyExamples.Generator.FromList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromList: \n\n    fromList [ 1, 2, 3, 4, 5 ]\n    |> advance 5\n    |> Tuple.first\n    --> [1, 2, 3, 4, 5]" <|
        \() ->
            Expect.equal
                (
                fromList [ 1, 2, 3, 4, 5 ]
                |> advance 5
                |> Tuple.first
                )
                (
                [1, 2, 3, 4, 5]
                )