module VerifyExamples.Generator.Head0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#head: \n\n    repeat 1\n    |> head\n    --> Just 1" <|
        \() ->
            Expect.equal
                (
                repeat 1
                |> head
                )
                (
                Just 1
                )