module VerifyExamples.Generator.Init0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#init: \n\n    init 1 (\\n -> Just (n, n+1))\n    |> advance 5\n    |> Tuple.first\n    --> [1, 2, 3, 4, 5]" <|
        \() ->
            Expect.equal
                (
                init 1 (\n -> Just (n, n+1))
                |> advance 5
                |> Tuple.first
                )
                (
                [1, 2, 3, 4, 5]
                )