module VerifyExamples.Generator.Inspect1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#inspect: \n\n    fromList [1, 2, 3, 4, 5]\n    |> drop 6\n    |> inspect\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                fromList [1, 2, 3, 4, 5]
                |> drop 6
                |> inspect
                )
                (
                Nothing
                )