module VerifyExamples.Generator.Interleave0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#interleave: \n\n    interleave (repeat 1) (repeat 2)\n    |> take 6\n    --> [1, 2, 1, 2, 1, 2]" <|
        \() ->
            Expect.equal
                (
                interleave (repeat 1) (repeat 2)
                |> take 6
                )
                (
                [1, 2, 1, 2, 1, 2]
                )