module VerifyExamples.Generator.Iterate0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#iterate: \n\n    iterate ((+) 1) 1\n    |> advance 5\n    |> Tuple.first\n    --> [1, 2, 3, 4, 5]" <|
        \() ->
            Expect.equal
                (
                iterate ((+) 1) 1
                |> advance 5
                |> Tuple.first
                )
                (
                [1, 2, 3, 4, 5]
                )