module VerifyExamples.Generator.Merge0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#merge: \n\n    fromList [ 1, 3, 4, 8 ]\n    |> (\\g1 -> ( g1, fromList [ 2, 3, 5, 7 ] ))\n    |> (\\(g1, g2) -> merge (<) g1 g2)\n    |> toList\n    --> [1, 2, 3, 3, 4, 5, 7, 8]" <|
        \() ->
            Expect.equal
                (
                fromList [ 1, 3, 4, 8 ]
                |> (\g1 -> ( g1, fromList [ 2, 3, 5, 7 ] ))
                |> (\(g1, g2) -> merge (<) g1 g2)
                |> toList
                )
                (
                [1, 2, 3, 3, 4, 5, 7, 8]
                )