module VerifyExamples.Generator.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    cycle [1, 2, 3]\n    |> take 6\n    --> [1, 2, 3, 1, 2, 3]" <|
        \() ->
            Expect.equal
                (
                cycle [1, 2, 3]
                |> take 6
                )
                (
                [1, 2, 3, 1, 2, 3]
                )