module VerifyExamples.Generator.Prefix0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#prefix: \n\n    prefix [1, 2, 3] (fromList [4, 5, 6])\n    |> take 6\n    --> [1, 2, 3, 4, 5, 6]" <|
        \() ->
            Expect.equal
                (
                prefix [1, 2, 3] (fromList [4, 5, 6])
                |> take 6
                )
                (
                [1, 2, 3, 4, 5, 6]
                )