module VerifyExamples.Generator.Scanl0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#scanl: \n\n    fromList [ 1, 2, 3 ]\n    |> scanl (+) 0\n    |> take 4\n    --> [1, 3, 6]" <|
        \() ->
            Expect.equal
                (
                fromList [ 1, 2, 3 ]
                |> scanl (+) 0
                |> take 4
                )
                (
                [1, 3, 6]
                )