module VerifyExamples.Generator.Tail0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#tail: \n\n    iterate ((+) 1) 1\n    |> tail\n    |> head\n    --> Just 2" <|
        \() ->
            Expect.equal
                (
                iterate ((+) 1) 1
                |> tail
                |> head
                )
                (
                Just 2
                )