module VerifyExamples.Generator.Zip0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#zip: \n\n    iterate ((+) 1) 1\n    |> (\\g -> zip g g)\n    |> take 3\n    --> [(1, 1), (2, 2), (3, 3)]" <|
        \() ->
            Expect.equal
                (
                iterate ((+) 1) 1
                |> (\g -> zip g g)
                |> take 3
                )
                (
                [(1, 1), (2, 2), (3, 3)]
                )