module VerifyExamples.Generator.ZipWith1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Generator exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#zipWith: \n\n    iterate ((+) 1) 1\n    |> (\\g -> zipWith (+) g g)\n    |> take 5\n    --> [2, 4, 6, 8, 10]" <|
        \() ->
            Expect.equal
                (
                iterate ((+) 1) 1
                |> (\g -> zipWith (+) g g)
                |> take 5
                )
                (
                [2, 4, 6, 8, 10]
                )